apiVersion: v1
kind: Secret 
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjMK
  MYSQL_DATABASE: YmFua2FwcGRi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
   MYSQL_DATABASE: "bankappdb"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
   name: mysql_sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fstype: ext4
reclaimPolicy: Retain
volumeBindingMode: waitForFirstConsumer
---

apiVersion: v1
kind: PersistenceVolumeClaim
metadata:
   name: mysql_pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql_sc
  resources:
    requests:
     storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
spec:
  selector:
    matchlabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
    labels:
      app: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
      resources:
        requests:
          memory: "512mi"
          cpu: "500m"
        limits:
           memory: "1Gi"
           cpu: "1"
      env:
      - name: MYSQL_ROOT_PASSWORD
        valuesFrom:
          secretKeyRef:
            name: mysql-secret
            value: MYSQL_ROOT_PASSWORD
      - name: MYSQL_DATABASE
        valuesFrom:
          configMapKeyRef:
            name: mysql_cm
            value: MYSQL_DATABASE
      ports:
        containerPort: 3306
        name: mysql
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: mysql-data
      volumes:
        persistenceVolumeClaim:
          claimName: mysql_pvc
    
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec:
  ports:
  - port: 3306
    targetPort: 3006
  selector:
   app: mysql
       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchlables:
      app: bankapp
  # strategy: Recreate
  template:
    metadata:
    labels:
      app: bankapp
    spec:
      containers:
      - name: bankapp
        image: adijaiswal/bankapp:latest
      resources:
        requests:
          memory: "512mi"
          cpu: "500mi"
        limits:
          memory: "1Gi"
          cpu: "1"
      env:
      - name: SPRING_DATASOURCE_URL
        value: 
        name: SPRING_DATASOURCE_USERNAME
        value: root
        name: SPRINCE_DATASOURCE_PASSWORD
        valueFrom:
        secretKeyRef:
          name: mysql-secret
          value: MYSQL_ROOT_PASSWORD
      ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: bankapp-service
spec:
  type: loadbalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp


      

        

  




       
       
